# permissions for end users to edit singularityjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: singularityjob-editor-role
rules:
- apiGroups:
  - azure.microsoft.com
  resources:
  - singularityjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - azure.microsoft.com
  resources:
  - singularityjobs/status
  verbs:
  - get
