# permissions for end users to view singularityaccounts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: singularityaccount-viewer-role
rules:
- apiGroups:
  - azure.microsoft.com
  resources:
  - singularityaccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - azure.microsoft.com
  resources:
  - singularityaccounts/status
  verbs:
  - get
