apiVersion: v1
entries:
  azure-service-operator:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2020-10-27T21:25:16.3414287-07:00"
    dependencies:
    - condition: installAadPodIdentity
      name: aad-pod-identity
      repository: https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts
      version: 1.5.5
    description: Deploy components and dependencies of azure-service-operator
    digest: c4bcdf1ac38e4e40fe9e749f0d402709edeb429afa6d4f83c3d2fd86f55525e7
    home: https://github.com/Azure/azure-service-operator
    name: azure-service-operator
    sources:
    - https://github.com/Azure/azure-service-operator
    urls:
    - azure-service-operator-0.1.0.tgz
    version: 0.1.0
generated: "2020-10-27T21:25:16.3383297-07:00"
