apiVersion: azure.microsoft.com/v1alpha1
kind: SingularityAccount
metadata:
  name: aso-singularityaccount-sample
spec:
  location: westus2
  resourceGroup: aso-resourcegroup-azure-operators
  locations:
    - name: westus2
      failoverPriority: 1
    - name: eastus
      failoverPriority: 2
  description: test-description