package microsoftazuremanagementaisupercomputer

// Copyright (c) Microsoft and contributors.  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
    "github.com/Azure/go-autorest/autorest"
    "github.com/Azure/go-autorest/autorest/azure"
    "net/http"
    "context"
    "github.com/Azure/go-autorest/tracing"
)

// GroupPolicyClient is the aISupercomputer Management Client
type GroupPolicyClient struct {
    BaseClient
}
// NewGroupPolicyClient creates an instance of the GroupPolicyClient client.
func NewGroupPolicyClient(subscriptionID string) GroupPolicyClient {
    return NewGroupPolicyClientWithBaseURI(DefaultBaseURI, subscriptionID)
}

// NewGroupPolicyClientWithBaseURI creates an instance of the GroupPolicyClient client using a custom endpoint.  Use
// this when interacting with an Azure cloud that uses a non-standard base URI (sovereign clouds, Azure stack).
    func NewGroupPolicyClientWithBaseURI(baseURI string, subscriptionID string) GroupPolicyClient {
        return GroupPolicyClient{ NewWithBaseURI(baseURI, subscriptionID)}
    }

// CreateOrUpdate creates a group policy resource with the specified name, description and properties. If a resource
// with the same name exists, then it is updated with the specified description and properties.
    // Parameters:
        // resourceGroupName - the name of the resource group within the user's subscription.
        // accountName - the name of the Singularity account.
        // policyName - the name of the Singularity account quota policy. Should only be Default.
        // body - singularity group policy quota limit information.
func (client GroupPolicyClient) CreateOrUpdate(ctx context.Context, resourceGroupName string, accountName string, policyName string, body GroupPolicyResourceDescription) (result GroupPolicyCreateOrUpdateFuture, err error) {
    if tracing.IsEnabled() {
        ctx = tracing.StartSpan(ctx, fqdn + "/GroupPolicyClient.CreateOrUpdate")
        defer func() {
            sc := -1
        if result.Response() != nil {
        sc = result.Response().StatusCode
        }
            tracing.EndSpan(ctx, sc, err)
        }()
    }
    req, err := client.CreateOrUpdatePreparer(ctx, resourceGroupName, accountName, policyName, body)
    if err != nil {
    err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.GroupPolicyClient", "CreateOrUpdate", nil , "Failure preparing request")
    return
    }

        result, err = client.CreateOrUpdateSender(req)
        if err != nil {
        err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.GroupPolicyClient", "CreateOrUpdate", result.Response(), "Failure sending request")
        return
        }

    return
}

    // CreateOrUpdatePreparer prepares the CreateOrUpdate request.
    func (client GroupPolicyClient) CreateOrUpdatePreparer(ctx context.Context, resourceGroupName string, accountName string, policyName string, body GroupPolicyResourceDescription) (*http.Request, error) {
        pathParameters := map[string]interface{} {
        "accountName": accountName,
        "policyName": policyName,
        "resourceGroupName": resourceGroupName,
        "subscriptionId": autorest.Encode("path",client.SubscriptionID),
        }

            const APIVersion = "2020-12-01-preview"
    queryParameters := map[string]interface{} {
    "api-version": APIVersion,
    }

    preparer := autorest.CreatePreparer(
autorest.AsContentType("application/json; charset=utf-8"),
autorest.AsPut(),
autorest.WithBaseURL(client.BaseURI),
autorest.WithPathParameters("/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.AISupercomputer/accounts/{accountName}/groupPolicies/{policyName}",pathParameters),
autorest.WithJSON(body),
autorest.WithQueryParameters(queryParameters))
    return preparer.Prepare((&http.Request{}).WithContext(ctx))
    }

    // CreateOrUpdateSender sends the CreateOrUpdate request. The method will close the
    // http.Response Body if it receives an error.
    func (client GroupPolicyClient) CreateOrUpdateSender(req *http.Request) (future GroupPolicyCreateOrUpdateFuture, err error) {
            var resp *http.Response
            resp, err = client.Send(req, azure.DoRetryWithRegistration(client.Client))
            if err != nil {
            return
            }
            future.Future, err = azure.NewFutureFromResponse(resp)
            return
            }

    // CreateOrUpdateResponder handles the response to the CreateOrUpdate request. The method always
    // closes the http.Response Body.
    func (client GroupPolicyClient) CreateOrUpdateResponder(resp *http.Response) (result GroupPolicyResourceDescription, err error) {
            err = autorest.Respond(
            resp,
            azure.WithErrorUnlessStatusCode(http.StatusOK,http.StatusCreated,http.StatusAccepted),
            autorest.ByUnmarshallingJSON(&result),
            autorest.ByClosing())
            result.Response = autorest.Response{Response: resp}
            return
    }

// Delete deletes a group policy resource with the specified name.
    // Parameters:
        // resourceGroupName - the name of the resource group within the user's subscription.
        // accountName - the name of the Singularity account.
        // policyName - the name of the Singularity account quota policy. Should only be Default.
func (client GroupPolicyClient) Delete(ctx context.Context, resourceGroupName string, accountName string, policyName string) (result GroupPolicyDeleteFuture, err error) {
    if tracing.IsEnabled() {
        ctx = tracing.StartSpan(ctx, fqdn + "/GroupPolicyClient.Delete")
        defer func() {
            sc := -1
        if result.Response() != nil {
        sc = result.Response().StatusCode
        }
            tracing.EndSpan(ctx, sc, err)
        }()
    }
    req, err := client.DeletePreparer(ctx, resourceGroupName, accountName, policyName)
    if err != nil {
    err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.GroupPolicyClient", "Delete", nil , "Failure preparing request")
    return
    }

        result, err = client.DeleteSender(req)
        if err != nil {
        err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.GroupPolicyClient", "Delete", result.Response(), "Failure sending request")
        return
        }

    return
}

    // DeletePreparer prepares the Delete request.
    func (client GroupPolicyClient) DeletePreparer(ctx context.Context, resourceGroupName string, accountName string, policyName string) (*http.Request, error) {
        pathParameters := map[string]interface{} {
        "accountName": accountName,
        "policyName": policyName,
        "resourceGroupName": resourceGroupName,
        "subscriptionId": autorest.Encode("path",client.SubscriptionID),
        }

            const APIVersion = "2020-12-01-preview"
    queryParameters := map[string]interface{} {
    "api-version": APIVersion,
    }

    preparer := autorest.CreatePreparer(
autorest.AsDelete(),
autorest.WithBaseURL(client.BaseURI),
autorest.WithPathParameters("/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.AISupercomputer/accounts/{accountName}/groupPolicies/{policyName}",pathParameters),
autorest.WithQueryParameters(queryParameters))
    return preparer.Prepare((&http.Request{}).WithContext(ctx))
    }

    // DeleteSender sends the Delete request. The method will close the
    // http.Response Body if it receives an error.
    func (client GroupPolicyClient) DeleteSender(req *http.Request) (future GroupPolicyDeleteFuture, err error) {
            var resp *http.Response
            resp, err = client.Send(req, azure.DoRetryWithRegistration(client.Client))
            if err != nil {
            return
            }
            future.Future, err = azure.NewFutureFromResponse(resp)
            return
            }

    // DeleteResponder handles the response to the Delete request. The method always
    // closes the http.Response Body.
    func (client GroupPolicyClient) DeleteResponder(resp *http.Response) (result autorest.Response, err error) {
            err = autorest.Respond(
            resp,
            azure.WithErrorUnlessStatusCode(http.StatusOK,http.StatusAccepted,http.StatusNoContent),
            autorest.ByClosing())
            result.Response = resp
            return
    }

// Get get a group policy resource with the specified name. The information include the description and other
// properties of the resource.
    // Parameters:
        // resourceGroupName - the name of the resource group within the user's subscription.
        // accountName - the name of the Singularity account.
        // policyName - the name of the Singularity account quota policy. Should only be Default.
func (client GroupPolicyClient) Get(ctx context.Context, resourceGroupName string, accountName string, policyName string) (result GroupPolicyResourceDescription, err error) {
    if tracing.IsEnabled() {
        ctx = tracing.StartSpan(ctx, fqdn + "/GroupPolicyClient.Get")
        defer func() {
            sc := -1
        if result.Response.Response != nil {
        sc = result.Response.Response.StatusCode
        }
            tracing.EndSpan(ctx, sc, err)
        }()
    }
    req, err := client.GetPreparer(ctx, resourceGroupName, accountName, policyName)
    if err != nil {
    err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.GroupPolicyClient", "Get", nil , "Failure preparing request")
    return
    }

        resp, err := client.GetSender(req)
        if err != nil {
        result.Response = autorest.Response{Response: resp}
        err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.GroupPolicyClient", "Get", resp, "Failure sending request")
        return
        }

        result, err = client.GetResponder(resp)
        if err != nil {
        err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.GroupPolicyClient", "Get", resp, "Failure responding to request")
        }

    return
}

    // GetPreparer prepares the Get request.
    func (client GroupPolicyClient) GetPreparer(ctx context.Context, resourceGroupName string, accountName string, policyName string) (*http.Request, error) {
        pathParameters := map[string]interface{} {
        "accountName": accountName,
        "policyName": policyName,
        "resourceGroupName": resourceGroupName,
        "subscriptionId": autorest.Encode("path",client.SubscriptionID),
        }

            const APIVersion = "2020-12-01-preview"
    queryParameters := map[string]interface{} {
    "api-version": APIVersion,
    }

    preparer := autorest.CreatePreparer(
autorest.AsGet(),
autorest.WithBaseURL(client.BaseURI),
autorest.WithPathParameters("/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.AISupercomputer/accounts/{accountName}/groupPolicies/{policyName}",pathParameters),
autorest.WithQueryParameters(queryParameters))
    return preparer.Prepare((&http.Request{}).WithContext(ctx))
    }

    // GetSender sends the Get request. The method will close the
    // http.Response Body if it receives an error.
    func (client GroupPolicyClient) GetSender(req *http.Request) (*http.Response, error) {
            return client.Send(req, azure.DoRetryWithRegistration(client.Client))
            }

    // GetResponder handles the response to the Get request. The method always
    // closes the http.Response Body.
    func (client GroupPolicyClient) GetResponder(resp *http.Response) (result GroupPolicyResourceDescription, err error) {
            err = autorest.Respond(
            resp,
            azure.WithErrorUnlessStatusCode(http.StatusOK),
            autorest.ByUnmarshallingJSON(&result),
            autorest.ByClosing())
            result.Response = autorest.Response{Response: resp}
            return
    }

// ListByAccount get all group policy resources in an account. The information include the description and other
// properties of the resource.
    // Parameters:
        // resourceGroupName - the name of the resource group within the user's subscription.
        // accountName - the name of the Singularity account.
func (client GroupPolicyClient) ListByAccount(ctx context.Context, resourceGroupName string, accountName string) (result GroupPolicyResourceDescriptionListPage, err error) {
    if tracing.IsEnabled() {
        ctx = tracing.StartSpan(ctx, fqdn + "/GroupPolicyClient.ListByAccount")
        defer func() {
            sc := -1
        if result.gprdl.Response.Response != nil {
        sc = result.gprdl.Response.Response.StatusCode
        }
            tracing.EndSpan(ctx, sc, err)
        }()
    }
        result.fn = client.listByAccountNextResults
    req, err := client.ListByAccountPreparer(ctx, resourceGroupName, accountName)
    if err != nil {
    err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.GroupPolicyClient", "ListByAccount", nil , "Failure preparing request")
    return
    }

        resp, err := client.ListByAccountSender(req)
        if err != nil {
        result.gprdl.Response = autorest.Response{Response: resp}
        err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.GroupPolicyClient", "ListByAccount", resp, "Failure sending request")
        return
        }

        result.gprdl, err = client.ListByAccountResponder(resp)
        if err != nil {
        err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.GroupPolicyClient", "ListByAccount", resp, "Failure responding to request")
        }
            if result.gprdl.hasNextLink() && result.gprdl.IsEmpty() {
            err = result.NextWithContext(ctx)
            }

    return
}

    // ListByAccountPreparer prepares the ListByAccount request.
    func (client GroupPolicyClient) ListByAccountPreparer(ctx context.Context, resourceGroupName string, accountName string) (*http.Request, error) {
        pathParameters := map[string]interface{} {
        "accountName": accountName,
        "resourceGroupName": resourceGroupName,
        "subscriptionId": autorest.Encode("path",client.SubscriptionID),
        }

            const APIVersion = "2020-12-01-preview"
    queryParameters := map[string]interface{} {
    "api-version": APIVersion,
    }

    preparer := autorest.CreatePreparer(
autorest.AsGet(),
autorest.WithBaseURL(client.BaseURI),
autorest.WithPathParameters("/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.AISupercomputer/accounts/{accountName}/groupPolicies",pathParameters),
autorest.WithQueryParameters(queryParameters))
    return preparer.Prepare((&http.Request{}).WithContext(ctx))
    }

    // ListByAccountSender sends the ListByAccount request. The method will close the
    // http.Response Body if it receives an error.
    func (client GroupPolicyClient) ListByAccountSender(req *http.Request) (*http.Response, error) {
            return client.Send(req, azure.DoRetryWithRegistration(client.Client))
            }

    // ListByAccountResponder handles the response to the ListByAccount request. The method always
    // closes the http.Response Body.
    func (client GroupPolicyClient) ListByAccountResponder(resp *http.Response) (result GroupPolicyResourceDescriptionList, err error) {
            err = autorest.Respond(
            resp,
            azure.WithErrorUnlessStatusCode(http.StatusOK),
            autorest.ByUnmarshallingJSON(&result),
            autorest.ByClosing())
            result.Response = autorest.Response{Response: resp}
            return
    }

            // listByAccountNextResults retrieves the next set of results, if any.
            func (client GroupPolicyClient) listByAccountNextResults(ctx context.Context, lastResults GroupPolicyResourceDescriptionList) (result GroupPolicyResourceDescriptionList, err error) {
            req, err := lastResults.groupPolicyResourceDescriptionListPreparer(ctx)
            if err != nil {
            return result, autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.GroupPolicyClient", "listByAccountNextResults", nil , "Failure preparing next results request")
            }
            if req == nil {
            return
            }
            resp, err := client.ListByAccountSender(req)
            if err != nil {
            result.Response = autorest.Response{Response: resp}
            return result, autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.GroupPolicyClient", "listByAccountNextResults", resp, "Failure sending next results request")
            }
            result, err = client.ListByAccountResponder(resp)
            if err != nil {
            err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.GroupPolicyClient", "listByAccountNextResults", resp, "Failure responding to next results request")
            }
            return
                    }

            // ListByAccountComplete enumerates all values, automatically crossing page boundaries as required.
            func (client GroupPolicyClient) ListByAccountComplete(ctx context.Context, resourceGroupName string, accountName string) (result GroupPolicyResourceDescriptionListIterator, err error) {
            if tracing.IsEnabled() {
            ctx = tracing.StartSpan(ctx, fqdn + "/GroupPolicyClient.ListByAccount")
            defer func() {
            sc := -1
            if result.Response().Response.Response != nil {
            sc = result.page.Response().Response.Response.StatusCode
            }
            tracing.EndSpan(ctx, sc, err)
            }()
            }
                    result.page, err = client.ListByAccount(ctx, resourceGroupName, accountName)
                            return
            }

// Update if a resource with the same name exists, then it is updated with the specified description and properties.
    // Parameters:
        // resourceGroupName - the name of the resource group within the user's subscription.
        // accountName - the name of the Singularity account.
        // policyName - the name of the Singularity account quota policy. Should only be Default.
        // body - singularity group policy quota limit information.
func (client GroupPolicyClient) Update(ctx context.Context, resourceGroupName string, accountName string, policyName string, body GroupPolicyResourcePatchDescription) (result GroupPolicyUpdateFuture, err error) {
    if tracing.IsEnabled() {
        ctx = tracing.StartSpan(ctx, fqdn + "/GroupPolicyClient.Update")
        defer func() {
            sc := -1
        if result.Response() != nil {
        sc = result.Response().StatusCode
        }
            tracing.EndSpan(ctx, sc, err)
        }()
    }
    req, err := client.UpdatePreparer(ctx, resourceGroupName, accountName, policyName, body)
    if err != nil {
    err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.GroupPolicyClient", "Update", nil , "Failure preparing request")
    return
    }

        result, err = client.UpdateSender(req)
        if err != nil {
        err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.GroupPolicyClient", "Update", result.Response(), "Failure sending request")
        return
        }

    return
}

    // UpdatePreparer prepares the Update request.
    func (client GroupPolicyClient) UpdatePreparer(ctx context.Context, resourceGroupName string, accountName string, policyName string, body GroupPolicyResourcePatchDescription) (*http.Request, error) {
        pathParameters := map[string]interface{} {
        "accountName": accountName,
        "policyName": policyName,
        "resourceGroupName": resourceGroupName,
        "subscriptionId": autorest.Encode("path",client.SubscriptionID),
        }

            const APIVersion = "2020-12-01-preview"
    queryParameters := map[string]interface{} {
    "api-version": APIVersion,
    }

    preparer := autorest.CreatePreparer(
autorest.AsContentType("application/json; charset=utf-8"),
autorest.AsPatch(),
autorest.WithBaseURL(client.BaseURI),
autorest.WithPathParameters("/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.AISupercomputer/accounts/{accountName}/groupPolicies/{policyName}",pathParameters),
autorest.WithJSON(body),
autorest.WithQueryParameters(queryParameters))
    return preparer.Prepare((&http.Request{}).WithContext(ctx))
    }

    // UpdateSender sends the Update request. The method will close the
    // http.Response Body if it receives an error.
    func (client GroupPolicyClient) UpdateSender(req *http.Request) (future GroupPolicyUpdateFuture, err error) {
            var resp *http.Response
            resp, err = client.Send(req, azure.DoRetryWithRegistration(client.Client))
            if err != nil {
            return
            }
            future.Future, err = azure.NewFutureFromResponse(resp)
            return
            }

    // UpdateResponder handles the response to the Update request. The method always
    // closes the http.Response Body.
    func (client GroupPolicyClient) UpdateResponder(resp *http.Response) (result GroupPolicyResourceDescription, err error) {
            err = autorest.Respond(
            resp,
            azure.WithErrorUnlessStatusCode(http.StatusOK,http.StatusCreated,http.StatusAccepted),
            autorest.ByUnmarshallingJSON(&result),
            autorest.ByClosing())
            result.Response = autorest.Response{Response: resp}
            return
    }

