package microsoftazuremanagementaisupercomputer

// Copyright (c) Microsoft and contributors.  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
    "github.com/Azure/go-autorest/autorest"
    "github.com/Azure/go-autorest/autorest/azure"
    "net/http"
    "context"
    "github.com/Azure/go-autorest/tracing"
    "github.com/Azure/go-autorest/autorest/validation"
)

// JobClient is the aISupercomputer Management Client
type JobClient struct {
    BaseClient
}
// NewJobClient creates an instance of the JobClient client.
func NewJobClient(subscriptionID string) JobClient {
    return NewJobClientWithBaseURI(DefaultBaseURI, subscriptionID)
}

// NewJobClientWithBaseURI creates an instance of the JobClient client using a custom endpoint.  Use this when
// interacting with an Azure cloud that uses a non-standard base URI (sovereign clouds, Azure stack).
    func NewJobClientWithBaseURI(baseURI string, subscriptionID string) JobClient {
        return JobClient{ NewWithBaseURI(baseURI, subscriptionID)}
    }

// Approve this action can be used by the account admin to approve a job manually, which is otherwise blocked by
// insufficient user-level quota (represented by Group Policy).
    // Parameters:
        // resourceGroupName - the name of the resource group within the user's subscription.
        // accountName - the name of the Singularity account.
        // jobName - the name of the Singularity job.
func (client JobClient) Approve(ctx context.Context, resourceGroupName string, accountName string, jobName string, body *JobUserActionDescription) (result JobApproveFuture, err error) {
    if tracing.IsEnabled() {
        ctx = tracing.StartSpan(ctx, fqdn + "/JobClient.Approve")
        defer func() {
            sc := -1
        if result.Response() != nil {
        sc = result.Response().StatusCode
        }
            tracing.EndSpan(ctx, sc, err)
        }()
    }
    req, err := client.ApprovePreparer(ctx, resourceGroupName, accountName, jobName, body)
    if err != nil {
    err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.JobClient", "Approve", nil , "Failure preparing request")
    return
    }

        result, err = client.ApproveSender(req)
        if err != nil {
        err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.JobClient", "Approve", result.Response(), "Failure sending request")
        return
        }

    return
}

    // ApprovePreparer prepares the Approve request.
    func (client JobClient) ApprovePreparer(ctx context.Context, resourceGroupName string, accountName string, jobName string, body *JobUserActionDescription) (*http.Request, error) {
        pathParameters := map[string]interface{} {
        "accountName": accountName,
        "jobName": jobName,
        "resourceGroupName": resourceGroupName,
        "subscriptionId": autorest.Encode("path",client.SubscriptionID),
        }

            const APIVersion = "2020-12-01-preview"
    queryParameters := map[string]interface{} {
    "api-version": APIVersion,
    }

    preparer := autorest.CreatePreparer(
autorest.AsContentType("application/json; charset=utf-8"),
autorest.AsPost(),
autorest.WithBaseURL(client.BaseURI),
autorest.WithPathParameters("/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.AISupercomputer/accounts/{accountName}/jobs/{jobName}/approve",pathParameters),
autorest.WithQueryParameters(queryParameters))
        if body != nil {
        preparer = autorest.DecoratePreparer(preparer,
        autorest.WithJSON(body))
        }
    return preparer.Prepare((&http.Request{}).WithContext(ctx))
    }

    // ApproveSender sends the Approve request. The method will close the
    // http.Response Body if it receives an error.
    func (client JobClient) ApproveSender(req *http.Request) (future JobApproveFuture, err error) {
            var resp *http.Response
            resp, err = client.Send(req, azure.DoRetryWithRegistration(client.Client))
            if err != nil {
            return
            }
            future.Future, err = azure.NewFutureFromResponse(resp)
            return
            }

    // ApproveResponder handles the response to the Approve request. The method always
    // closes the http.Response Body.
    func (client JobClient) ApproveResponder(resp *http.Response) (result autorest.Response, err error) {
            err = autorest.Respond(
            resp,
            azure.WithErrorUnlessStatusCode(http.StatusOK,http.StatusAccepted),
            autorest.ByClosing())
            result.Response = resp
            return
    }

// CreateOrUpdate creates a job resource with the specified name, description and properties. If a job with the same
// name exists, then it is updated with the specified description and properties.
    // Parameters:
        // resourceGroupName - the name of the resource group within the user's subscription.
        // accountName - the name of the Singularity account.
        // jobName - the name of the Singularity job.
        // body - singularity job information.
func (client JobClient) CreateOrUpdate(ctx context.Context, resourceGroupName string, accountName string, jobName string, body JobResourceDescription) (result JobCreateOrUpdateFuture, err error) {
    if tracing.IsEnabled() {
        ctx = tracing.StartSpan(ctx, fqdn + "/JobClient.CreateOrUpdate")
        defer func() {
            sc := -1
        if result.Response() != nil {
        sc = result.Response().StatusCode
        }
            tracing.EndSpan(ctx, sc, err)
        }()
    }
        if err := validation.Validate([]validation.Validation{
        { TargetValue: body,
         Constraints: []validation.Constraint{	{Target: "body.JobResourceDescriptionProperties", Name: validation.Null, Rule: true, Chain: nil },
        	{Target: "body.Identity", Name: validation.Null, Rule: false ,
        Chain: []validation.Constraint{	{Target: "body.Identity.Type", Name: validation.Null, Rule: true, Chain: nil },
        }}}}}); err != nil {
        return result, validation.NewError("microsoftazuremanagementaisupercomputer.JobClient", "CreateOrUpdate", err.Error())
        }

        req, err := client.CreateOrUpdatePreparer(ctx, resourceGroupName, accountName, jobName, body)
    if err != nil {
    err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.JobClient", "CreateOrUpdate", nil , "Failure preparing request")
    return
    }

        result, err = client.CreateOrUpdateSender(req)
        if err != nil {
        err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.JobClient", "CreateOrUpdate", result.Response(), "Failure sending request")
        return
        }

    return
}

    // CreateOrUpdatePreparer prepares the CreateOrUpdate request.
    func (client JobClient) CreateOrUpdatePreparer(ctx context.Context, resourceGroupName string, accountName string, jobName string, body JobResourceDescription) (*http.Request, error) {
        pathParameters := map[string]interface{} {
        "accountName": accountName,
        "jobName": jobName,
        "resourceGroupName": resourceGroupName,
        "subscriptionId": autorest.Encode("path",client.SubscriptionID),
        }

            const APIVersion = "2020-12-01-preview"
    queryParameters := map[string]interface{} {
    "api-version": APIVersion,
    }

    preparer := autorest.CreatePreparer(
autorest.AsContentType("application/json; charset=utf-8"),
autorest.AsPut(),
autorest.WithBaseURL(client.BaseURI),
autorest.WithPathParameters("/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.AISupercomputer/accounts/{accountName}/jobs/{jobName}",pathParameters),
autorest.WithJSON(body),
autorest.WithQueryParameters(queryParameters))
    return preparer.Prepare((&http.Request{}).WithContext(ctx))
    }

    // CreateOrUpdateSender sends the CreateOrUpdate request. The method will close the
    // http.Response Body if it receives an error.
    func (client JobClient) CreateOrUpdateSender(req *http.Request) (future JobCreateOrUpdateFuture, err error) {
            var resp *http.Response
            resp, err = client.Send(req, azure.DoRetryWithRegistration(client.Client))
            if err != nil {
            return
            }
            future.Future, err = azure.NewFutureFromResponse(resp)
            return
            }

    // CreateOrUpdateResponder handles the response to the CreateOrUpdate request. The method always
    // closes the http.Response Body.
    func (client JobClient) CreateOrUpdateResponder(resp *http.Response) (result JobResourceDescription, err error) {
            err = autorest.Respond(
            resp,
            azure.WithErrorUnlessStatusCode(http.StatusOK,http.StatusCreated,http.StatusAccepted),
            autorest.ByUnmarshallingJSON(&result),
            autorest.ByClosing())
            result.Response = autorest.Response{Response: resp}
            return
    }

// CreateSasToken creates a Shared Access Signature (SAS) token, that can be used for accessing job resource with the
// protocol specified in the description.
    // Parameters:
        // resourceGroupName - the name of the resource group within the user's subscription.
        // accountName - the name of the Singularity account.
        // jobName - the name of the Singularity job.
        // body - singularity job Shared Access Signature (SAS) token information.
func (client JobClient) CreateSasToken(ctx context.Context, resourceGroupName string, accountName string, jobName string, body *JobSasTokenDescription) (result JobCreateSasTokenFuture, err error) {
    if tracing.IsEnabled() {
        ctx = tracing.StartSpan(ctx, fqdn + "/JobClient.CreateSasToken")
        defer func() {
            sc := -1
        if result.Response() != nil {
        sc = result.Response().StatusCode
        }
            tracing.EndSpan(ctx, sc, err)
        }()
    }
    req, err := client.CreateSasTokenPreparer(ctx, resourceGroupName, accountName, jobName, body)
    if err != nil {
    err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.JobClient", "CreateSasToken", nil , "Failure preparing request")
    return
    }

        result, err = client.CreateSasTokenSender(req)
        if err != nil {
        err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.JobClient", "CreateSasToken", result.Response(), "Failure sending request")
        return
        }

    return
}

    // CreateSasTokenPreparer prepares the CreateSasToken request.
    func (client JobClient) CreateSasTokenPreparer(ctx context.Context, resourceGroupName string, accountName string, jobName string, body *JobSasTokenDescription) (*http.Request, error) {
        pathParameters := map[string]interface{} {
        "accountName": accountName,
        "jobName": jobName,
        "resourceGroupName": resourceGroupName,
        "subscriptionId": autorest.Encode("path",client.SubscriptionID),
        }

            const APIVersion = "2020-12-01-preview"
    queryParameters := map[string]interface{} {
    "api-version": APIVersion,
    }

            body.Version = nil
            body.Token = nil
    preparer := autorest.CreatePreparer(
autorest.AsContentType("application/json; charset=utf-8"),
autorest.AsPost(),
autorest.WithBaseURL(client.BaseURI),
autorest.WithPathParameters("/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.AISupercomputer/accounts/{accountName}/jobs/{jobName}/createsastoken",pathParameters),
autorest.WithQueryParameters(queryParameters))
        if body != nil {
        preparer = autorest.DecoratePreparer(preparer,
        autorest.WithJSON(body))
        }
    return preparer.Prepare((&http.Request{}).WithContext(ctx))
    }

    // CreateSasTokenSender sends the CreateSasToken request. The method will close the
    // http.Response Body if it receives an error.
    func (client JobClient) CreateSasTokenSender(req *http.Request) (future JobCreateSasTokenFuture, err error) {
            var resp *http.Response
            resp, err = client.Send(req, azure.DoRetryWithRegistration(client.Client))
            if err != nil {
            return
            }
            future.Future, err = azure.NewFutureFromResponse(resp)
            return
            }

    // CreateSasTokenResponder handles the response to the CreateSasToken request. The method always
    // closes the http.Response Body.
    func (client JobClient) CreateSasTokenResponder(resp *http.Response) (result JobSasTokenDescription, err error) {
            err = autorest.Respond(
            resp,
            azure.WithErrorUnlessStatusCode(http.StatusOK,http.StatusCreated),
            autorest.ByUnmarshallingJSON(&result),
            autorest.ByClosing())
            result.Response = autorest.Response{Response: resp}
            return
    }

// Delete deletes the job resource identified by the name.
    // Parameters:
        // resourceGroupName - the name of the resource group within the user's subscription.
        // accountName - the name of the Singularity account.
        // jobName - the name of the Singularity job.
func (client JobClient) Delete(ctx context.Context, resourceGroupName string, accountName string, jobName string) (result JobDeleteFuture, err error) {
    if tracing.IsEnabled() {
        ctx = tracing.StartSpan(ctx, fqdn + "/JobClient.Delete")
        defer func() {
            sc := -1
        if result.Response() != nil {
        sc = result.Response().StatusCode
        }
            tracing.EndSpan(ctx, sc, err)
        }()
    }
    req, err := client.DeletePreparer(ctx, resourceGroupName, accountName, jobName)
    if err != nil {
    err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.JobClient", "Delete", nil , "Failure preparing request")
    return
    }

        result, err = client.DeleteSender(req)
        if err != nil {
        err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.JobClient", "Delete", result.Response(), "Failure sending request")
        return
        }

    return
}

    // DeletePreparer prepares the Delete request.
    func (client JobClient) DeletePreparer(ctx context.Context, resourceGroupName string, accountName string, jobName string) (*http.Request, error) {
        pathParameters := map[string]interface{} {
        "accountName": accountName,
        "jobName": jobName,
        "resourceGroupName": resourceGroupName,
        "subscriptionId": autorest.Encode("path",client.SubscriptionID),
        }

            const APIVersion = "2020-12-01-preview"
    queryParameters := map[string]interface{} {
    "api-version": APIVersion,
    }

    preparer := autorest.CreatePreparer(
autorest.AsDelete(),
autorest.WithBaseURL(client.BaseURI),
autorest.WithPathParameters("/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.AISupercomputer/accounts/{accountName}/jobs/{jobName}",pathParameters),
autorest.WithQueryParameters(queryParameters))
    return preparer.Prepare((&http.Request{}).WithContext(ctx))
    }

    // DeleteSender sends the Delete request. The method will close the
    // http.Response Body if it receives an error.
    func (client JobClient) DeleteSender(req *http.Request) (future JobDeleteFuture, err error) {
            var resp *http.Response
            resp, err = client.Send(req, azure.DoRetryWithRegistration(client.Client))
            if err != nil {
            return
            }
            future.Future, err = azure.NewFutureFromResponse(resp)
            return
            }

    // DeleteResponder handles the response to the Delete request. The method always
    // closes the http.Response Body.
    func (client JobClient) DeleteResponder(resp *http.Response) (result autorest.Response, err error) {
            err = autorest.Respond(
            resp,
            azure.WithErrorUnlessStatusCode(http.StatusOK,http.StatusAccepted,http.StatusNoContent),
            autorest.ByClosing())
            result.Response = resp
            return
    }

// Get gets the information about the job resource with the given name. The information include the description and
// other properties of the job.
    // Parameters:
        // resourceGroupName - the name of the resource group within the user's subscription.
        // accountName - the name of the Singularity account.
        // jobName - the name of the Singularity job.
func (client JobClient) Get(ctx context.Context, resourceGroupName string, accountName string, jobName string) (result JobResourceDescription, err error) {
    if tracing.IsEnabled() {
        ctx = tracing.StartSpan(ctx, fqdn + "/JobClient.Get")
        defer func() {
            sc := -1
        if result.Response.Response != nil {
        sc = result.Response.Response.StatusCode
        }
            tracing.EndSpan(ctx, sc, err)
        }()
    }
    req, err := client.GetPreparer(ctx, resourceGroupName, accountName, jobName)
    if err != nil {
    err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.JobClient", "Get", nil , "Failure preparing request")
    return
    }

        resp, err := client.GetSender(req)
        if err != nil {
        result.Response = autorest.Response{Response: resp}
        err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.JobClient", "Get", resp, "Failure sending request")
        return
        }

        result, err = client.GetResponder(resp)
        if err != nil {
        err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.JobClient", "Get", resp, "Failure responding to request")
        }

    return
}

    // GetPreparer prepares the Get request.
    func (client JobClient) GetPreparer(ctx context.Context, resourceGroupName string, accountName string, jobName string) (*http.Request, error) {
        pathParameters := map[string]interface{} {
        "accountName": accountName,
        "jobName": jobName,
        "resourceGroupName": resourceGroupName,
        "subscriptionId": autorest.Encode("path",client.SubscriptionID),
        }

            const APIVersion = "2020-12-01-preview"
    queryParameters := map[string]interface{} {
    "api-version": APIVersion,
    }

    preparer := autorest.CreatePreparer(
autorest.AsGet(),
autorest.WithBaseURL(client.BaseURI),
autorest.WithPathParameters("/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.AISupercomputer/accounts/{accountName}/jobs/{jobName}",pathParameters),
autorest.WithQueryParameters(queryParameters))
    return preparer.Prepare((&http.Request{}).WithContext(ctx))
    }

    // GetSender sends the Get request. The method will close the
    // http.Response Body if it receives an error.
    func (client JobClient) GetSender(req *http.Request) (*http.Response, error) {
            return client.Send(req, azure.DoRetryWithRegistration(client.Client))
            }

    // GetResponder handles the response to the Get request. The method always
    // closes the http.Response Body.
    func (client JobClient) GetResponder(resp *http.Response) (result JobResourceDescription, err error) {
            err = autorest.Respond(
            resp,
            azure.WithErrorUnlessStatusCode(http.StatusOK),
            autorest.ByUnmarshallingJSON(&result),
            autorest.ByClosing())
            result.Response = autorest.Response{Response: resp}
            return
    }

// ListByAccount gets the information about all the job resources in a given account. The information include the
// description and other properties of the job.
    // Parameters:
        // resourceGroupName - the name of the resource group within the user's subscription.
        // accountName - the name of the Singularity account.
func (client JobClient) ListByAccount(ctx context.Context, resourceGroupName string, accountName string) (result JobResourceDescriptionListPage, err error) {
    if tracing.IsEnabled() {
        ctx = tracing.StartSpan(ctx, fqdn + "/JobClient.ListByAccount")
        defer func() {
            sc := -1
        if result.jrdl.Response.Response != nil {
        sc = result.jrdl.Response.Response.StatusCode
        }
            tracing.EndSpan(ctx, sc, err)
        }()
    }
        result.fn = client.listByAccountNextResults
    req, err := client.ListByAccountPreparer(ctx, resourceGroupName, accountName)
    if err != nil {
    err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.JobClient", "ListByAccount", nil , "Failure preparing request")
    return
    }

        resp, err := client.ListByAccountSender(req)
        if err != nil {
        result.jrdl.Response = autorest.Response{Response: resp}
        err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.JobClient", "ListByAccount", resp, "Failure sending request")
        return
        }

        result.jrdl, err = client.ListByAccountResponder(resp)
        if err != nil {
        err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.JobClient", "ListByAccount", resp, "Failure responding to request")
        }
            if result.jrdl.hasNextLink() && result.jrdl.IsEmpty() {
            err = result.NextWithContext(ctx)
            }

    return
}

    // ListByAccountPreparer prepares the ListByAccount request.
    func (client JobClient) ListByAccountPreparer(ctx context.Context, resourceGroupName string, accountName string) (*http.Request, error) {
        pathParameters := map[string]interface{} {
        "accountName": accountName,
        "resourceGroupName": resourceGroupName,
        "subscriptionId": autorest.Encode("path",client.SubscriptionID),
        }

            const APIVersion = "2020-12-01-preview"
    queryParameters := map[string]interface{} {
    "api-version": APIVersion,
    }

    preparer := autorest.CreatePreparer(
autorest.AsGet(),
autorest.WithBaseURL(client.BaseURI),
autorest.WithPathParameters("/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.AISupercomputer/accounts/{accountName}/jobs",pathParameters),
autorest.WithQueryParameters(queryParameters))
    return preparer.Prepare((&http.Request{}).WithContext(ctx))
    }

    // ListByAccountSender sends the ListByAccount request. The method will close the
    // http.Response Body if it receives an error.
    func (client JobClient) ListByAccountSender(req *http.Request) (*http.Response, error) {
            return client.Send(req, azure.DoRetryWithRegistration(client.Client))
            }

    // ListByAccountResponder handles the response to the ListByAccount request. The method always
    // closes the http.Response Body.
    func (client JobClient) ListByAccountResponder(resp *http.Response) (result JobResourceDescriptionList, err error) {
            err = autorest.Respond(
            resp,
            azure.WithErrorUnlessStatusCode(http.StatusOK),
            autorest.ByUnmarshallingJSON(&result),
            autorest.ByClosing())
            result.Response = autorest.Response{Response: resp}
            return
    }

            // listByAccountNextResults retrieves the next set of results, if any.
            func (client JobClient) listByAccountNextResults(ctx context.Context, lastResults JobResourceDescriptionList) (result JobResourceDescriptionList, err error) {
            req, err := lastResults.jobResourceDescriptionListPreparer(ctx)
            if err != nil {
            return result, autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.JobClient", "listByAccountNextResults", nil , "Failure preparing next results request")
            }
            if req == nil {
            return
            }
            resp, err := client.ListByAccountSender(req)
            if err != nil {
            result.Response = autorest.Response{Response: resp}
            return result, autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.JobClient", "listByAccountNextResults", resp, "Failure sending next results request")
            }
            result, err = client.ListByAccountResponder(resp)
            if err != nil {
            err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.JobClient", "listByAccountNextResults", resp, "Failure responding to next results request")
            }
            return
                    }

            // ListByAccountComplete enumerates all values, automatically crossing page boundaries as required.
            func (client JobClient) ListByAccountComplete(ctx context.Context, resourceGroupName string, accountName string) (result JobResourceDescriptionListIterator, err error) {
            if tracing.IsEnabled() {
            ctx = tracing.StartSpan(ctx, fqdn + "/JobClient.ListByAccount")
            defer func() {
            sc := -1
            if result.Response().Response.Response != nil {
            sc = result.page.Response().Response.Response.StatusCode
            }
            tracing.EndSpan(ctx, sc, err)
            }()
            }
                    result.page, err = client.ListByAccount(ctx, resourceGroupName, accountName)
                            return
            }

// Remove remove job operation is used to delete a job that is associated with a group policy.
    // Parameters:
        // resourceGroupName - the name of the resource group within the user's subscription.
        // accountName - the name of the Singularity account.
        // jobName - the name of the Singularity job.
func (client JobClient) Remove(ctx context.Context, resourceGroupName string, accountName string, jobName string, body *JobUserActionDescription) (result JobRemoveFuture, err error) {
    if tracing.IsEnabled() {
        ctx = tracing.StartSpan(ctx, fqdn + "/JobClient.Remove")
        defer func() {
            sc := -1
        if result.Response() != nil {
        sc = result.Response().StatusCode
        }
            tracing.EndSpan(ctx, sc, err)
        }()
    }
    req, err := client.RemovePreparer(ctx, resourceGroupName, accountName, jobName, body)
    if err != nil {
    err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.JobClient", "Remove", nil , "Failure preparing request")
    return
    }

        result, err = client.RemoveSender(req)
        if err != nil {
        err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.JobClient", "Remove", result.Response(), "Failure sending request")
        return
        }

    return
}

    // RemovePreparer prepares the Remove request.
    func (client JobClient) RemovePreparer(ctx context.Context, resourceGroupName string, accountName string, jobName string, body *JobUserActionDescription) (*http.Request, error) {
        pathParameters := map[string]interface{} {
        "accountName": accountName,
        "jobName": jobName,
        "resourceGroupName": resourceGroupName,
        "subscriptionId": autorest.Encode("path",client.SubscriptionID),
        }

            const APIVersion = "2020-12-01-preview"
    queryParameters := map[string]interface{} {
    "api-version": APIVersion,
    }

    preparer := autorest.CreatePreparer(
autorest.AsContentType("application/json; charset=utf-8"),
autorest.AsPost(),
autorest.WithBaseURL(client.BaseURI),
autorest.WithPathParameters("/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.AISupercomputer/accounts/{accountName}/jobs/{jobName}/remove",pathParameters),
autorest.WithQueryParameters(queryParameters))
        if body != nil {
        preparer = autorest.DecoratePreparer(preparer,
        autorest.WithJSON(body))
        }
    return preparer.Prepare((&http.Request{}).WithContext(ctx))
    }

    // RemoveSender sends the Remove request. The method will close the
    // http.Response Body if it receives an error.
    func (client JobClient) RemoveSender(req *http.Request) (future JobRemoveFuture, err error) {
            var resp *http.Response
            resp, err = client.Send(req, azure.DoRetryWithRegistration(client.Client))
            if err != nil {
            return
            }
            future.Future, err = azure.NewFutureFromResponse(resp)
            return
            }

    // RemoveResponder handles the response to the Remove request. The method always
    // closes the http.Response Body.
    func (client JobClient) RemoveResponder(resp *http.Response) (result autorest.Response, err error) {
            err = autorest.Respond(
            resp,
            azure.WithErrorUnlessStatusCode(http.StatusOK,http.StatusAccepted,http.StatusNoContent),
            autorest.ByClosing())
            result.Response = resp
            return
    }

// RenewKey renews to the Shared Access Signature (SAS) token singining key for the job. It invalidates all tokens
// generated prior to key rotation
    // Parameters:
        // resourceGroupName - the name of the resource group within the user's subscription.
        // accountName - the name of the Singularity account.
        // jobName - the name of the Singularity job.
func (client JobClient) RenewKey(ctx context.Context, resourceGroupName string, accountName string, jobName string) (result JobSasTokenDescription, err error) {
    if tracing.IsEnabled() {
        ctx = tracing.StartSpan(ctx, fqdn + "/JobClient.RenewKey")
        defer func() {
            sc := -1
        if result.Response.Response != nil {
        sc = result.Response.Response.StatusCode
        }
            tracing.EndSpan(ctx, sc, err)
        }()
    }
    req, err := client.RenewKeyPreparer(ctx, resourceGroupName, accountName, jobName)
    if err != nil {
    err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.JobClient", "RenewKey", nil , "Failure preparing request")
    return
    }

        resp, err := client.RenewKeySender(req)
        if err != nil {
        result.Response = autorest.Response{Response: resp}
        err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.JobClient", "RenewKey", resp, "Failure sending request")
        return
        }

        result, err = client.RenewKeyResponder(resp)
        if err != nil {
        err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.JobClient", "RenewKey", resp, "Failure responding to request")
        }

    return
}

    // RenewKeyPreparer prepares the RenewKey request.
    func (client JobClient) RenewKeyPreparer(ctx context.Context, resourceGroupName string, accountName string, jobName string) (*http.Request, error) {
        pathParameters := map[string]interface{} {
        "accountName": accountName,
        "jobName": jobName,
        "resourceGroupName": resourceGroupName,
        "subscriptionId": autorest.Encode("path",client.SubscriptionID),
        }

            const APIVersion = "2020-12-01-preview"
    queryParameters := map[string]interface{} {
    "api-version": APIVersion,
    }

    preparer := autorest.CreatePreparer(
autorest.AsPost(),
autorest.WithBaseURL(client.BaseURI),
autorest.WithPathParameters("/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.AISupercomputer/accounts/{accountName}/jobs/{jobName}/renewkey",pathParameters),
autorest.WithQueryParameters(queryParameters))
    return preparer.Prepare((&http.Request{}).WithContext(ctx))
    }

    // RenewKeySender sends the RenewKey request. The method will close the
    // http.Response Body if it receives an error.
    func (client JobClient) RenewKeySender(req *http.Request) (*http.Response, error) {
            return client.Send(req, azure.DoRetryWithRegistration(client.Client))
            }

    // RenewKeyResponder handles the response to the RenewKey request. The method always
    // closes the http.Response Body.
    func (client JobClient) RenewKeyResponder(resp *http.Response) (result JobSasTokenDescription, err error) {
            err = autorest.Respond(
            resp,
            azure.WithErrorUnlessStatusCode(http.StatusOK,http.StatusCreated),
            autorest.ByUnmarshallingJSON(&result),
            autorest.ByClosing())
            result.Response = autorest.Response{Response: resp}
            return
    }

// Resume resuming a paused job will attempt to return the job into the running state by reserving quota and scheduling
// execution.
    // Parameters:
        // resourceGroupName - the name of the resource group within the user's subscription.
        // accountName - the name of the Singularity account.
        // jobName - the name of the Singularity job.
func (client JobClient) Resume(ctx context.Context, resourceGroupName string, accountName string, jobName string, body *JobUserActionDescription) (result JobResumeFuture, err error) {
    if tracing.IsEnabled() {
        ctx = tracing.StartSpan(ctx, fqdn + "/JobClient.Resume")
        defer func() {
            sc := -1
        if result.Response() != nil {
        sc = result.Response().StatusCode
        }
            tracing.EndSpan(ctx, sc, err)
        }()
    }
    req, err := client.ResumePreparer(ctx, resourceGroupName, accountName, jobName, body)
    if err != nil {
    err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.JobClient", "Resume", nil , "Failure preparing request")
    return
    }

        result, err = client.ResumeSender(req)
        if err != nil {
        err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.JobClient", "Resume", result.Response(), "Failure sending request")
        return
        }

    return
}

    // ResumePreparer prepares the Resume request.
    func (client JobClient) ResumePreparer(ctx context.Context, resourceGroupName string, accountName string, jobName string, body *JobUserActionDescription) (*http.Request, error) {
        pathParameters := map[string]interface{} {
        "accountName": accountName,
        "jobName": jobName,
        "resourceGroupName": resourceGroupName,
        "subscriptionId": autorest.Encode("path",client.SubscriptionID),
        }

            const APIVersion = "2020-12-01-preview"
    queryParameters := map[string]interface{} {
    "api-version": APIVersion,
    }

    preparer := autorest.CreatePreparer(
autorest.AsContentType("application/json; charset=utf-8"),
autorest.AsPost(),
autorest.WithBaseURL(client.BaseURI),
autorest.WithPathParameters("/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.AISupercomputer/accounts/{accountName}/jobs/{jobName}/resume",pathParameters),
autorest.WithQueryParameters(queryParameters))
        if body != nil {
        preparer = autorest.DecoratePreparer(preparer,
        autorest.WithJSON(body))
        }
    return preparer.Prepare((&http.Request{}).WithContext(ctx))
    }

    // ResumeSender sends the Resume request. The method will close the
    // http.Response Body if it receives an error.
    func (client JobClient) ResumeSender(req *http.Request) (future JobResumeFuture, err error) {
            var resp *http.Response
            resp, err = client.Send(req, azure.DoRetryWithRegistration(client.Client))
            if err != nil {
            return
            }
            future.Future, err = azure.NewFutureFromResponse(resp)
            return
            }

    // ResumeResponder handles the response to the Resume request. The method always
    // closes the http.Response Body.
    func (client JobClient) ResumeResponder(resp *http.Response) (result autorest.Response, err error) {
            err = autorest.Respond(
            resp,
            azure.WithErrorUnlessStatusCode(http.StatusOK,http.StatusAccepted),
            autorest.ByClosing())
            result.Response = resp
            return
    }

// Suspend suspending a job will stop the current execution and release any resources and quota reservations. The job
// will remain in the Suspended state until resumed or deleted.
    // Parameters:
        // resourceGroupName - the name of the resource group within the user's subscription.
        // accountName - the name of the Singularity account.
        // jobName - the name of the Singularity job.
func (client JobClient) Suspend(ctx context.Context, resourceGroupName string, accountName string, jobName string, body *JobUserActionDescription) (result JobSuspendFuture, err error) {
    if tracing.IsEnabled() {
        ctx = tracing.StartSpan(ctx, fqdn + "/JobClient.Suspend")
        defer func() {
            sc := -1
        if result.Response() != nil {
        sc = result.Response().StatusCode
        }
            tracing.EndSpan(ctx, sc, err)
        }()
    }
    req, err := client.SuspendPreparer(ctx, resourceGroupName, accountName, jobName, body)
    if err != nil {
    err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.JobClient", "Suspend", nil , "Failure preparing request")
    return
    }

        result, err = client.SuspendSender(req)
        if err != nil {
        err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.JobClient", "Suspend", result.Response(), "Failure sending request")
        return
        }

    return
}

    // SuspendPreparer prepares the Suspend request.
    func (client JobClient) SuspendPreparer(ctx context.Context, resourceGroupName string, accountName string, jobName string, body *JobUserActionDescription) (*http.Request, error) {
        pathParameters := map[string]interface{} {
        "accountName": accountName,
        "jobName": jobName,
        "resourceGroupName": resourceGroupName,
        "subscriptionId": autorest.Encode("path",client.SubscriptionID),
        }

            const APIVersion = "2020-12-01-preview"
    queryParameters := map[string]interface{} {
    "api-version": APIVersion,
    }

    preparer := autorest.CreatePreparer(
autorest.AsContentType("application/json; charset=utf-8"),
autorest.AsPost(),
autorest.WithBaseURL(client.BaseURI),
autorest.WithPathParameters("/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.AISupercomputer/accounts/{accountName}/jobs/{jobName}/suspend",pathParameters),
autorest.WithQueryParameters(queryParameters))
        if body != nil {
        preparer = autorest.DecoratePreparer(preparer,
        autorest.WithJSON(body))
        }
    return preparer.Prepare((&http.Request{}).WithContext(ctx))
    }

    // SuspendSender sends the Suspend request. The method will close the
    // http.Response Body if it receives an error.
    func (client JobClient) SuspendSender(req *http.Request) (future JobSuspendFuture, err error) {
            var resp *http.Response
            resp, err = client.Send(req, azure.DoRetryWithRegistration(client.Client))
            if err != nil {
            return
            }
            future.Future, err = azure.NewFutureFromResponse(resp)
            return
            }

    // SuspendResponder handles the response to the Suspend request. The method always
    // closes the http.Response Body.
    func (client JobClient) SuspendResponder(resp *http.Response) (result autorest.Response, err error) {
            err = autorest.Respond(
            resp,
            azure.WithErrorUnlessStatusCode(http.StatusOK,http.StatusAccepted),
            autorest.ByClosing())
            result.Response = resp
            return
    }

// Update updates a job resource with the specified properties. If a job with the same name exists, then it is updated
// with the specified properties. If a job doesn't exist, then a no-content exception will be thrown
    // Parameters:
        // resourceGroupName - the name of the resource group within the user's subscription.
        // accountName - the name of the Singularity account.
        // jobName - the name of the Singularity job.
        // body - singularity job information.
func (client JobClient) Update(ctx context.Context, resourceGroupName string, accountName string, jobName string, body JobResourcePatchDescription) (result JobUpdateFuture, err error) {
    if tracing.IsEnabled() {
        ctx = tracing.StartSpan(ctx, fqdn + "/JobClient.Update")
        defer func() {
            sc := -1
        if result.Response() != nil {
        sc = result.Response().StatusCode
        }
            tracing.EndSpan(ctx, sc, err)
        }()
    }
    req, err := client.UpdatePreparer(ctx, resourceGroupName, accountName, jobName, body)
    if err != nil {
    err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.JobClient", "Update", nil , "Failure preparing request")
    return
    }

        result, err = client.UpdateSender(req)
        if err != nil {
        err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.JobClient", "Update", result.Response(), "Failure sending request")
        return
        }

    return
}

    // UpdatePreparer prepares the Update request.
    func (client JobClient) UpdatePreparer(ctx context.Context, resourceGroupName string, accountName string, jobName string, body JobResourcePatchDescription) (*http.Request, error) {
        pathParameters := map[string]interface{} {
        "accountName": accountName,
        "jobName": jobName,
        "resourceGroupName": resourceGroupName,
        "subscriptionId": autorest.Encode("path",client.SubscriptionID),
        }

            const APIVersion = "2020-12-01-preview"
    queryParameters := map[string]interface{} {
    "api-version": APIVersion,
    }

    preparer := autorest.CreatePreparer(
autorest.AsContentType("application/json; charset=utf-8"),
autorest.AsPatch(),
autorest.WithBaseURL(client.BaseURI),
autorest.WithPathParameters("/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.AISupercomputer/accounts/{accountName}/jobs/{jobName}",pathParameters),
autorest.WithJSON(body),
autorest.WithQueryParameters(queryParameters))
    return preparer.Prepare((&http.Request{}).WithContext(ctx))
    }

    // UpdateSender sends the Update request. The method will close the
    // http.Response Body if it receives an error.
    func (client JobClient) UpdateSender(req *http.Request) (future JobUpdateFuture, err error) {
            var resp *http.Response
            resp, err = client.Send(req, azure.DoRetryWithRegistration(client.Client))
            if err != nil {
            return
            }
            future.Future, err = azure.NewFutureFromResponse(resp)
            return
            }

    // UpdateResponder handles the response to the Update request. The method always
    // closes the http.Response Body.
    func (client JobClient) UpdateResponder(resp *http.Response) (result JobResourceDescription, err error) {
            err = autorest.Respond(
            resp,
            azure.WithErrorUnlessStatusCode(http.StatusOK,http.StatusCreated,http.StatusAccepted),
            autorest.ByUnmarshallingJSON(&result),
            autorest.ByClosing())
            result.Response = autorest.Response{Response: resp}
            return
    }

