package microsoftazuremanagementaisupercomputer

// Copyright (c) Microsoft and contributors.  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
    "github.com/Azure/go-autorest/autorest"
    "github.com/Azure/go-autorest/autorest/azure"
    "net/http"
    "context"
    "github.com/Azure/go-autorest/tracing"
    "github.com/Azure/go-autorest/autorest/validation"
)

// StorageContainerClient is the aISupercomputer Management Client
type StorageContainerClient struct {
    BaseClient
}
// NewStorageContainerClient creates an instance of the StorageContainerClient client.
func NewStorageContainerClient(subscriptionID string) StorageContainerClient {
    return NewStorageContainerClientWithBaseURI(DefaultBaseURI, subscriptionID)
}

// NewStorageContainerClientWithBaseURI creates an instance of the StorageContainerClient client using a custom
// endpoint.  Use this when interacting with an Azure cloud that uses a non-standard base URI (sovereign clouds, Azure
// stack).
    func NewStorageContainerClientWithBaseURI(baseURI string, subscriptionID string) StorageContainerClient {
        return StorageContainerClient{ NewWithBaseURI(baseURI, subscriptionID)}
    }

// CreateOrUpdate creates a storage container resource with the specified name, description and properties. If a
// storage container resource with the same name exists, then it is updated with the specified description and
// properties.
    // Parameters:
        // resourceGroupName - the name of the resource group within the user's subscription.
        // accountName - the name of the Singularity account.
        // storageContainerResourceName - the name of the Singularity storage container.
        // body - singularity storage container information.
func (client StorageContainerClient) CreateOrUpdate(ctx context.Context, resourceGroupName string, accountName string, storageContainerResourceName string, body StorageContainerResourceDescription) (result StorageContainerCreateOrUpdateFuture, err error) {
    if tracing.IsEnabled() {
        ctx = tracing.StartSpan(ctx, fqdn + "/StorageContainerClient.CreateOrUpdate")
        defer func() {
            sc := -1
        if result.Response() != nil {
        sc = result.Response().StatusCode
        }
            tracing.EndSpan(ctx, sc, err)
        }()
    }
        if err := validation.Validate([]validation.Validation{
        { TargetValue: body,
         Constraints: []validation.Constraint{	{Target: "body.StorageContainerResourceDescriptionProperties", Name: validation.Null, Rule: true, Chain: nil }}}}); err != nil {
        return result, validation.NewError("microsoftazuremanagementaisupercomputer.StorageContainerClient", "CreateOrUpdate", err.Error())
        }

        req, err := client.CreateOrUpdatePreparer(ctx, resourceGroupName, accountName, storageContainerResourceName, body)
    if err != nil {
    err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.StorageContainerClient", "CreateOrUpdate", nil , "Failure preparing request")
    return
    }

        result, err = client.CreateOrUpdateSender(req)
        if err != nil {
        err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.StorageContainerClient", "CreateOrUpdate", result.Response(), "Failure sending request")
        return
        }

    return
}

    // CreateOrUpdatePreparer prepares the CreateOrUpdate request.
    func (client StorageContainerClient) CreateOrUpdatePreparer(ctx context.Context, resourceGroupName string, accountName string, storageContainerResourceName string, body StorageContainerResourceDescription) (*http.Request, error) {
        pathParameters := map[string]interface{} {
        "accountName": accountName,
        "resourceGroupName": resourceGroupName,
        "storageContainerResourceName": storageContainerResourceName,
        "subscriptionId": autorest.Encode("path",client.SubscriptionID),
        }

            const APIVersion = "2020-12-01-preview"
    queryParameters := map[string]interface{} {
    "api-version": APIVersion,
    }

    preparer := autorest.CreatePreparer(
autorest.AsContentType("application/json; charset=utf-8"),
autorest.AsPut(),
autorest.WithBaseURL(client.BaseURI),
autorest.WithPathParameters("/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.AISupercomputer/accounts/{accountName}/storagecontainers/{storageContainerResourceName}",pathParameters),
autorest.WithJSON(body),
autorest.WithQueryParameters(queryParameters))
    return preparer.Prepare((&http.Request{}).WithContext(ctx))
    }

    // CreateOrUpdateSender sends the CreateOrUpdate request. The method will close the
    // http.Response Body if it receives an error.
    func (client StorageContainerClient) CreateOrUpdateSender(req *http.Request) (future StorageContainerCreateOrUpdateFuture, err error) {
            var resp *http.Response
            resp, err = client.Send(req, azure.DoRetryWithRegistration(client.Client))
            if err != nil {
            return
            }
            future.Future, err = azure.NewFutureFromResponse(resp)
            return
            }

    // CreateOrUpdateResponder handles the response to the CreateOrUpdate request. The method always
    // closes the http.Response Body.
    func (client StorageContainerClient) CreateOrUpdateResponder(resp *http.Response) (result StorageContainerResourceDescription, err error) {
            err = autorest.Respond(
            resp,
            azure.WithErrorUnlessStatusCode(http.StatusOK,http.StatusCreated,http.StatusAccepted),
            autorest.ByUnmarshallingJSON(&result),
            autorest.ByClosing())
            result.Response = autorest.Response{Response: resp}
            return
    }

// Delete deletes the storage container resource identified by the name.
    // Parameters:
        // resourceGroupName - the name of the resource group within the user's subscription.
        // accountName - the name of the Singularity account.
        // storageContainerResourceName - the name of the Singularity storage container.
func (client StorageContainerClient) Delete(ctx context.Context, resourceGroupName string, accountName string, storageContainerResourceName string) (result StorageContainerDeleteFuture, err error) {
    if tracing.IsEnabled() {
        ctx = tracing.StartSpan(ctx, fqdn + "/StorageContainerClient.Delete")
        defer func() {
            sc := -1
        if result.Response() != nil {
        sc = result.Response().StatusCode
        }
            tracing.EndSpan(ctx, sc, err)
        }()
    }
    req, err := client.DeletePreparer(ctx, resourceGroupName, accountName, storageContainerResourceName)
    if err != nil {
    err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.StorageContainerClient", "Delete", nil , "Failure preparing request")
    return
    }

        result, err = client.DeleteSender(req)
        if err != nil {
        err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.StorageContainerClient", "Delete", result.Response(), "Failure sending request")
        return
        }

    return
}

    // DeletePreparer prepares the Delete request.
    func (client StorageContainerClient) DeletePreparer(ctx context.Context, resourceGroupName string, accountName string, storageContainerResourceName string) (*http.Request, error) {
        pathParameters := map[string]interface{} {
        "accountName": accountName,
        "resourceGroupName": resourceGroupName,
        "storageContainerResourceName": storageContainerResourceName,
        "subscriptionId": autorest.Encode("path",client.SubscriptionID),
        }

            const APIVersion = "2020-12-01-preview"
    queryParameters := map[string]interface{} {
    "api-version": APIVersion,
    }

    preparer := autorest.CreatePreparer(
autorest.AsDelete(),
autorest.WithBaseURL(client.BaseURI),
autorest.WithPathParameters("/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.AISupercomputer/accounts/{accountName}/storagecontainers/{storageContainerResourceName}",pathParameters),
autorest.WithQueryParameters(queryParameters))
    return preparer.Prepare((&http.Request{}).WithContext(ctx))
    }

    // DeleteSender sends the Delete request. The method will close the
    // http.Response Body if it receives an error.
    func (client StorageContainerClient) DeleteSender(req *http.Request) (future StorageContainerDeleteFuture, err error) {
            var resp *http.Response
            resp, err = client.Send(req, azure.DoRetryWithRegistration(client.Client))
            if err != nil {
            return
            }
            future.Future, err = azure.NewFutureFromResponse(resp)
            return
            }

    // DeleteResponder handles the response to the Delete request. The method always
    // closes the http.Response Body.
    func (client StorageContainerClient) DeleteResponder(resp *http.Response) (result autorest.Response, err error) {
            err = autorest.Respond(
            resp,
            azure.WithErrorUnlessStatusCode(http.StatusOK,http.StatusAccepted,http.StatusNoContent),
            autorest.ByClosing())
            result.Response = resp
            return
    }

// Get gets the information about the storage container resource with the given name. The information include the
// description and other properties of the storage container.
    // Parameters:
        // resourceGroupName - the name of the resource group within the user's subscription.
        // accountName - the name of the Singularity account.
        // storageContainerResourceName - the name of the Singularity storage container.
func (client StorageContainerClient) Get(ctx context.Context, resourceGroupName string, accountName string, storageContainerResourceName string) (result StorageContainerResourceDescription, err error) {
    if tracing.IsEnabled() {
        ctx = tracing.StartSpan(ctx, fqdn + "/StorageContainerClient.Get")
        defer func() {
            sc := -1
        if result.Response.Response != nil {
        sc = result.Response.Response.StatusCode
        }
            tracing.EndSpan(ctx, sc, err)
        }()
    }
    req, err := client.GetPreparer(ctx, resourceGroupName, accountName, storageContainerResourceName)
    if err != nil {
    err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.StorageContainerClient", "Get", nil , "Failure preparing request")
    return
    }

        resp, err := client.GetSender(req)
        if err != nil {
        result.Response = autorest.Response{Response: resp}
        err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.StorageContainerClient", "Get", resp, "Failure sending request")
        return
        }

        result, err = client.GetResponder(resp)
        if err != nil {
        err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.StorageContainerClient", "Get", resp, "Failure responding to request")
        }

    return
}

    // GetPreparer prepares the Get request.
    func (client StorageContainerClient) GetPreparer(ctx context.Context, resourceGroupName string, accountName string, storageContainerResourceName string) (*http.Request, error) {
        pathParameters := map[string]interface{} {
        "accountName": accountName,
        "resourceGroupName": resourceGroupName,
        "storageContainerResourceName": storageContainerResourceName,
        "subscriptionId": autorest.Encode("path",client.SubscriptionID),
        }

            const APIVersion = "2020-12-01-preview"
    queryParameters := map[string]interface{} {
    "api-version": APIVersion,
    }

    preparer := autorest.CreatePreparer(
autorest.AsGet(),
autorest.WithBaseURL(client.BaseURI),
autorest.WithPathParameters("/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.AISupercomputer/accounts/{accountName}/storagecontainers/{storageContainerResourceName}",pathParameters),
autorest.WithQueryParameters(queryParameters))
    return preparer.Prepare((&http.Request{}).WithContext(ctx))
    }

    // GetSender sends the Get request. The method will close the
    // http.Response Body if it receives an error.
    func (client StorageContainerClient) GetSender(req *http.Request) (*http.Response, error) {
            return client.Send(req, azure.DoRetryWithRegistration(client.Client))
            }

    // GetResponder handles the response to the Get request. The method always
    // closes the http.Response Body.
    func (client StorageContainerClient) GetResponder(resp *http.Response) (result StorageContainerResourceDescription, err error) {
            err = autorest.Respond(
            resp,
            azure.WithErrorUnlessStatusCode(http.StatusOK),
            autorest.ByUnmarshallingJSON(&result),
            autorest.ByClosing())
            result.Response = autorest.Response{Response: resp}
            return
    }

// ListByAccount gets the information about all storage container resources in a given account. The information include
// the description and other properties of the storage container.
    // Parameters:
        // resourceGroupName - the name of the resource group within the user's subscription.
        // accountName - the name of the Singularity account.
func (client StorageContainerClient) ListByAccount(ctx context.Context, resourceGroupName string, accountName string) (result StorageContainerResourceDescriptionListPage, err error) {
    if tracing.IsEnabled() {
        ctx = tracing.StartSpan(ctx, fqdn + "/StorageContainerClient.ListByAccount")
        defer func() {
            sc := -1
        if result.scrdl.Response.Response != nil {
        sc = result.scrdl.Response.Response.StatusCode
        }
            tracing.EndSpan(ctx, sc, err)
        }()
    }
        result.fn = client.listByAccountNextResults
    req, err := client.ListByAccountPreparer(ctx, resourceGroupName, accountName)
    if err != nil {
    err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.StorageContainerClient", "ListByAccount", nil , "Failure preparing request")
    return
    }

        resp, err := client.ListByAccountSender(req)
        if err != nil {
        result.scrdl.Response = autorest.Response{Response: resp}
        err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.StorageContainerClient", "ListByAccount", resp, "Failure sending request")
        return
        }

        result.scrdl, err = client.ListByAccountResponder(resp)
        if err != nil {
        err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.StorageContainerClient", "ListByAccount", resp, "Failure responding to request")
        }
            if result.scrdl.hasNextLink() && result.scrdl.IsEmpty() {
            err = result.NextWithContext(ctx)
            }

    return
}

    // ListByAccountPreparer prepares the ListByAccount request.
    func (client StorageContainerClient) ListByAccountPreparer(ctx context.Context, resourceGroupName string, accountName string) (*http.Request, error) {
        pathParameters := map[string]interface{} {
        "accountName": accountName,
        "resourceGroupName": resourceGroupName,
        "subscriptionId": autorest.Encode("path",client.SubscriptionID),
        }

            const APIVersion = "2020-12-01-preview"
    queryParameters := map[string]interface{} {
    "api-version": APIVersion,
    }

    preparer := autorest.CreatePreparer(
autorest.AsGet(),
autorest.WithBaseURL(client.BaseURI),
autorest.WithPathParameters("/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.AISupercomputer/accounts/{accountName}/storagecontainers",pathParameters),
autorest.WithQueryParameters(queryParameters))
    return preparer.Prepare((&http.Request{}).WithContext(ctx))
    }

    // ListByAccountSender sends the ListByAccount request. The method will close the
    // http.Response Body if it receives an error.
    func (client StorageContainerClient) ListByAccountSender(req *http.Request) (*http.Response, error) {
            return client.Send(req, azure.DoRetryWithRegistration(client.Client))
            }

    // ListByAccountResponder handles the response to the ListByAccount request. The method always
    // closes the http.Response Body.
    func (client StorageContainerClient) ListByAccountResponder(resp *http.Response) (result StorageContainerResourceDescriptionList, err error) {
            err = autorest.Respond(
            resp,
            azure.WithErrorUnlessStatusCode(http.StatusOK),
            autorest.ByUnmarshallingJSON(&result),
            autorest.ByClosing())
            result.Response = autorest.Response{Response: resp}
            return
    }

            // listByAccountNextResults retrieves the next set of results, if any.
            func (client StorageContainerClient) listByAccountNextResults(ctx context.Context, lastResults StorageContainerResourceDescriptionList) (result StorageContainerResourceDescriptionList, err error) {
            req, err := lastResults.storageContainerResourceDescriptionListPreparer(ctx)
            if err != nil {
            return result, autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.StorageContainerClient", "listByAccountNextResults", nil , "Failure preparing next results request")
            }
            if req == nil {
            return
            }
            resp, err := client.ListByAccountSender(req)
            if err != nil {
            result.Response = autorest.Response{Response: resp}
            return result, autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.StorageContainerClient", "listByAccountNextResults", resp, "Failure sending next results request")
            }
            result, err = client.ListByAccountResponder(resp)
            if err != nil {
            err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.StorageContainerClient", "listByAccountNextResults", resp, "Failure responding to next results request")
            }
            return
                    }

            // ListByAccountComplete enumerates all values, automatically crossing page boundaries as required.
            func (client StorageContainerClient) ListByAccountComplete(ctx context.Context, resourceGroupName string, accountName string) (result StorageContainerResourceDescriptionListIterator, err error) {
            if tracing.IsEnabled() {
            ctx = tracing.StartSpan(ctx, fqdn + "/StorageContainerClient.ListByAccount")
            defer func() {
            sc := -1
            if result.Response().Response.Response != nil {
            sc = result.page.Response().Response.Response.StatusCode
            }
            tracing.EndSpan(ctx, sc, err)
            }()
            }
                    result.page, err = client.ListByAccount(ctx, resourceGroupName, accountName)
                            return
            }

// Resume resumes the storage container resource identified by the name.
    // Parameters:
        // resourceGroupName - the name of the resource group within the user's subscription.
        // accountName - the name of the Singularity account.
        // storageContainerResourceName - the name of the Singularity storage container.
func (client StorageContainerClient) Resume(ctx context.Context, resourceGroupName string, accountName string, storageContainerResourceName string) (result StorageContainerResumeFuture, err error) {
    if tracing.IsEnabled() {
        ctx = tracing.StartSpan(ctx, fqdn + "/StorageContainerClient.Resume")
        defer func() {
            sc := -1
        if result.Response() != nil {
        sc = result.Response().StatusCode
        }
            tracing.EndSpan(ctx, sc, err)
        }()
    }
    req, err := client.ResumePreparer(ctx, resourceGroupName, accountName, storageContainerResourceName)
    if err != nil {
    err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.StorageContainerClient", "Resume", nil , "Failure preparing request")
    return
    }

        result, err = client.ResumeSender(req)
        if err != nil {
        err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.StorageContainerClient", "Resume", result.Response(), "Failure sending request")
        return
        }

    return
}

    // ResumePreparer prepares the Resume request.
    func (client StorageContainerClient) ResumePreparer(ctx context.Context, resourceGroupName string, accountName string, storageContainerResourceName string) (*http.Request, error) {
        pathParameters := map[string]interface{} {
        "accountName": accountName,
        "resourceGroupName": resourceGroupName,
        "storageContainerResourceName": storageContainerResourceName,
        "subscriptionId": autorest.Encode("path",client.SubscriptionID),
        }

            const APIVersion = "2020-12-01-preview"
    queryParameters := map[string]interface{} {
    "api-version": APIVersion,
    }

    preparer := autorest.CreatePreparer(
autorest.AsPost(),
autorest.WithBaseURL(client.BaseURI),
autorest.WithPathParameters("/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.AISupercomputer/accounts/{accountName}/storagecontainers/{storageContainerResourceName}/resume",pathParameters),
autorest.WithQueryParameters(queryParameters))
    return preparer.Prepare((&http.Request{}).WithContext(ctx))
    }

    // ResumeSender sends the Resume request. The method will close the
    // http.Response Body if it receives an error.
    func (client StorageContainerClient) ResumeSender(req *http.Request) (future StorageContainerResumeFuture, err error) {
            var resp *http.Response
            resp, err = client.Send(req, azure.DoRetryWithRegistration(client.Client))
            if err != nil {
            return
            }
            future.Future, err = azure.NewFutureFromResponse(resp)
            return
            }

    // ResumeResponder handles the response to the Resume request. The method always
    // closes the http.Response Body.
    func (client StorageContainerClient) ResumeResponder(resp *http.Response) (result StorageContainerResourceDescription, err error) {
            err = autorest.Respond(
            resp,
            azure.WithErrorUnlessStatusCode(http.StatusOK,http.StatusAccepted,http.StatusNoContent),
            autorest.ByUnmarshallingJSON(&result),
            autorest.ByClosing())
            result.Response = autorest.Response{Response: resp}
            return
    }

// Suspend suspends the storage container resource identified by the name.
    // Parameters:
        // resourceGroupName - the name of the resource group within the user's subscription.
        // accountName - the name of the Singularity account.
        // storageContainerResourceName - the name of the Singularity storage container.
func (client StorageContainerClient) Suspend(ctx context.Context, resourceGroupName string, accountName string, storageContainerResourceName string) (result StorageContainerSuspendFuture, err error) {
    if tracing.IsEnabled() {
        ctx = tracing.StartSpan(ctx, fqdn + "/StorageContainerClient.Suspend")
        defer func() {
            sc := -1
        if result.Response() != nil {
        sc = result.Response().StatusCode
        }
            tracing.EndSpan(ctx, sc, err)
        }()
    }
    req, err := client.SuspendPreparer(ctx, resourceGroupName, accountName, storageContainerResourceName)
    if err != nil {
    err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.StorageContainerClient", "Suspend", nil , "Failure preparing request")
    return
    }

        result, err = client.SuspendSender(req)
        if err != nil {
        err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.StorageContainerClient", "Suspend", result.Response(), "Failure sending request")
        return
        }

    return
}

    // SuspendPreparer prepares the Suspend request.
    func (client StorageContainerClient) SuspendPreparer(ctx context.Context, resourceGroupName string, accountName string, storageContainerResourceName string) (*http.Request, error) {
        pathParameters := map[string]interface{} {
        "accountName": accountName,
        "resourceGroupName": resourceGroupName,
        "storageContainerResourceName": storageContainerResourceName,
        "subscriptionId": autorest.Encode("path",client.SubscriptionID),
        }

            const APIVersion = "2020-12-01-preview"
    queryParameters := map[string]interface{} {
    "api-version": APIVersion,
    }

    preparer := autorest.CreatePreparer(
autorest.AsPost(),
autorest.WithBaseURL(client.BaseURI),
autorest.WithPathParameters("/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.AISupercomputer/accounts/{accountName}/storagecontainers/{storageContainerResourceName}/suspend",pathParameters),
autorest.WithQueryParameters(queryParameters))
    return preparer.Prepare((&http.Request{}).WithContext(ctx))
    }

    // SuspendSender sends the Suspend request. The method will close the
    // http.Response Body if it receives an error.
    func (client StorageContainerClient) SuspendSender(req *http.Request) (future StorageContainerSuspendFuture, err error) {
            var resp *http.Response
            resp, err = client.Send(req, azure.DoRetryWithRegistration(client.Client))
            if err != nil {
            return
            }
            future.Future, err = azure.NewFutureFromResponse(resp)
            return
            }

    // SuspendResponder handles the response to the Suspend request. The method always
    // closes the http.Response Body.
    func (client StorageContainerClient) SuspendResponder(resp *http.Response) (result StorageContainerResourceDescription, err error) {
            err = autorest.Respond(
            resp,
            azure.WithErrorUnlessStatusCode(http.StatusOK,http.StatusAccepted,http.StatusNoContent),
            autorest.ByUnmarshallingJSON(&result),
            autorest.ByClosing())
            result.Response = autorest.Response{Response: resp}
            return
    }

// Update if a storage container resource with the same name exists, then it is updated with the specified description
// and properties.
    // Parameters:
        // resourceGroupName - the name of the resource group within the user's subscription.
        // accountName - the name of the Singularity account.
        // storageContainerResourceName - the name of the Singularity storage container.
        // body - singularity storage container information.
func (client StorageContainerClient) Update(ctx context.Context, resourceGroupName string, accountName string, storageContainerResourceName string, body StorageContainerResourcePatchDescription) (result StorageContainerUpdateFuture, err error) {
    if tracing.IsEnabled() {
        ctx = tracing.StartSpan(ctx, fqdn + "/StorageContainerClient.Update")
        defer func() {
            sc := -1
        if result.Response() != nil {
        sc = result.Response().StatusCode
        }
            tracing.EndSpan(ctx, sc, err)
        }()
    }
    req, err := client.UpdatePreparer(ctx, resourceGroupName, accountName, storageContainerResourceName, body)
    if err != nil {
    err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.StorageContainerClient", "Update", nil , "Failure preparing request")
    return
    }

        result, err = client.UpdateSender(req)
        if err != nil {
        err = autorest.NewErrorWithError(err, "microsoftazuremanagementaisupercomputer.StorageContainerClient", "Update", result.Response(), "Failure sending request")
        return
        }

    return
}

    // UpdatePreparer prepares the Update request.
    func (client StorageContainerClient) UpdatePreparer(ctx context.Context, resourceGroupName string, accountName string, storageContainerResourceName string, body StorageContainerResourcePatchDescription) (*http.Request, error) {
        pathParameters := map[string]interface{} {
        "accountName": accountName,
        "resourceGroupName": resourceGroupName,
        "storageContainerResourceName": storageContainerResourceName,
        "subscriptionId": autorest.Encode("path",client.SubscriptionID),
        }

            const APIVersion = "2020-12-01-preview"
    queryParameters := map[string]interface{} {
    "api-version": APIVersion,
    }

    preparer := autorest.CreatePreparer(
autorest.AsContentType("application/json; charset=utf-8"),
autorest.AsPatch(),
autorest.WithBaseURL(client.BaseURI),
autorest.WithPathParameters("/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.AISupercomputer/accounts/{accountName}/storagecontainers/{storageContainerResourceName}",pathParameters),
autorest.WithJSON(body),
autorest.WithQueryParameters(queryParameters))
    return preparer.Prepare((&http.Request{}).WithContext(ctx))
    }

    // UpdateSender sends the Update request. The method will close the
    // http.Response Body if it receives an error.
    func (client StorageContainerClient) UpdateSender(req *http.Request) (future StorageContainerUpdateFuture, err error) {
            var resp *http.Response
            resp, err = client.Send(req, azure.DoRetryWithRegistration(client.Client))
            if err != nil {
            return
            }
            future.Future, err = azure.NewFutureFromResponse(resp)
            return
            }

    // UpdateResponder handles the response to the Update request. The method always
    // closes the http.Response Body.
    func (client StorageContainerClient) UpdateResponder(resp *http.Response) (result StorageContainerResourceDescription, err error) {
            err = autorest.Respond(
            resp,
            azure.WithErrorUnlessStatusCode(http.StatusOK,http.StatusCreated,http.StatusAccepted),
            autorest.ByUnmarshallingJSON(&result),
            autorest.ByClosing())
            result.Response = autorest.Response{Response: resp}
            return
    }

